YONK-805: Users view APIs for mobile app resource
edx-solutions/mobileapps-edx-platform-extensions pull request #2
Opened 2017-10-30 16:08 UTC by aamishbaloch

Changes include view for users view APIs for mobile app resource, through which users can be added or removed from the mobile apps. Unit tests are also included.

2017-10-30 16:09 UTC, aamishbaloch commented
@ziafazal Can you review this?

2017-10-31 07:15 UTC, ziafazal requested changes
@aamishbaloch completed first round of review.

2017-10-31 07:15 UTC, ziafazal commented on mobileapps/views.py
> +        * users_id: comma separated list of user ids to add into the mobile app
rename `user_id` should be `users`

2017-10-31 07:15 UTC, ziafazal commented on mobileapps/views.py
> +        * users_id: comma separated list of user ids to add into the mobile app
We need to add docstring for DELETE method too.

2017-10-31 07:15 UTC, ziafazal commented on mobileapps/views.py
> +            [mobileapp.users.add(user) for user in User.objects.filter(id__in=user_ids)]
what about simplifying this operation like this
```
for user in User.objects.filter(id__in=user_ids)
    mobileapp.users.add(user)
```

2017-10-31 07:15 UTC, ziafazal commented on mobileapps/views.py
> +        queryset = User.objects.filter(mobile_apps__exact=self.kwargs['mobileapp_id'])
nit: just return here.

2017-10-31 07:15 UTC, ziafazal commented on mobileapps/tests.py
> +    def test_mobileapps_users(self):
We need to create a separate test Class for mobile apps users tests.

2017-10-31 07:15 UTC, ziafazal commented on mobileapps/tests.py
> +        mobileapp.users.add(*users)
I think to make this test more close to real test case we should create at-least two mobile apps and distribute users among them.

2017-10-31 07:15 UTC, ziafazal commented on mobileapps/views.py
> +            return Response({}, status=status.HTTP_200_OK)
Http status code here should be 201.

2017-10-31 07:15 UTC, ziafazal commented on mobileapps/views.py
> +            return Response({}, status=status.HTTP_200_OK)
Http status code here should be 204.

2017-10-31 07:15 UTC, ziafazal commented on mobileapps/tests.py
> +        mobileapp = MobileApp.objects.create(
add a `setupClass` method of the test case class and add these operations into that
```
 mobileapp = MobileApp.objects.create(
            name='ABC App',
            identifier='ABC',
            operating_system=self.test_mobileapp_operating_system,
            current_version=self.test_mobileapp_current_version,
            updated_by=self.user,
        )

        users = UserFactory.create_batch(5)
        mobileapp.users.add(*users)
```

2017-10-31 08:14 UTC, aamishbaloch commented
@ziafazal Done with the suggested changes, Can you review the changes?

2017-10-31 08:33 UTC, ziafazal approved these changes
👍

2017-10-31 08:53 UTC, merged