push notifications views added to send push notifications to mobile apps
edx-solutions/mobileapps-edx-platform-extensions pull request #4
Opened 2017-11-01 10:20 UTC by ihtram

2017-11-01 10:20 UTC, ihtram commented
@ziafazal can you please review this pull request?

2017-11-01 11:48 UTC, ziafazal requested changes
@ihtram completed first round of review.

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/tasks.py
> +                                           channel_context=api_keys)
`channel_context` is a dict and we should have provider_credentials in it `api_credentials` key.

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/utils.py
> +def get_api_keys(mobile_app):
This should be a model method of `MobileApp` model  instead of util method

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/utils.py
> +def get_provider_name(mobile_app):
This should be a model method of `MobileApp` model  instead of util method.

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/views.py
> +from django.utils.translation import ugettext_lazy as _
It appears import order does not conform to pep8 in this file
http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#id12

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/views.py
> +        using urban airship push notification backend.
These APIs are not only for urban airship so wording here should be something
```
using app's push notifications provider
```

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/views.py
> +        * title: notification title
For push notifications we don't need title. Only `message` param is needed.

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/views.py
> +                payload={'title': title,
set `title` key to message text and remove `message` key of payload here since it is not going to be used.

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/views.py
> +        using urban airship push notification backend.
These APIs are not only for urban airship so wording needs to be changed here too.

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/views.py
> +        * title: notification title
`title` is not needed here too.

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/views.py
> +            notification_type = get_notification_type(u'open-edx.mobileapps.notifications')
we should make a new method which should make a push notification message with `title` and `app_identifier` params and should reuse that method all over.

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/views.py
> +class MobileAppAllUsersNotifications(SecureListCreateAPIView):
I think these APIs should inherit from `SecureCreateAPIView` since we are not listing anything here.

2017-11-01 11:48 UTC, ziafazal commented on mobileapps/views.py
> +        organization of the app using urban airship push notification backend.
urban airship wording.

2017-11-01 15:14 UTC, ihtram commented
@ziafazal i have implemented the above mentioned changes. can you please review again?

2017-11-02 07:35 UTC, ziafazal requested changes
@ihtram completed second round of review.

2017-11-02 07:35 UTC, ziafazal commented on mobileapps/urls.py
> +    url(r'^(?P<pk>[0-9]+)/organization/(?P<organization_id>[0-9]+)/notification$',
why we changed parameter name from `mobile_app_id` to `pk`?

2017-11-02 07:35 UTC, ziafazal commented on mobileapps/views.py
> +            if not notification_provider:
Can we move this block of code little up where we are checking if mobile app is active?.

2017-11-02 07:35 UTC, ziafazal commented on mobileapps/views.py
> +            if not notification_provider:
nit: move this check little up.

2017-11-02 07:35 UTC, ziafazal commented on mobileapps/views.py
> +def _create_notification_message(title, app_identifier, send_to_all=False):
This method should have two params `app_identifier ` and `payload`. It would make it more generic we can pass whatever payload we want to.

2017-11-02 07:35 UTC, ziafazal commented on mobileapps/models.py
> +    def get_notifications_provider(self):
I think we should rename this method to `get_notification_provider_name`

2017-11-02 08:09 UTC, ihtram commented
@ziafazal  the above mentioned changed have been implemented

2017-11-02 08:28 UTC, ziafazal approved these changes
👍

2017-11-02 09:41 UTC, merged