adding tests for push notifications apis
edx-solutions/mobileapps-edx-platform-extensions pull request #6
Opened 2017-11-02 14:23 UTC by ihtram

2017-11-02 14:24 UTC, ihtram commented
@ziafazal  i have added tests for mobile apps notifications. can you please review?

2017-11-02 14:35 UTC, ziafazal requested changes
@ihtram one suggestion other than that looks good.

2017-11-02 14:35 UTC, ziafazal commented on mobileapps/tests.py
> +    def setUp(self):
Can we move the logic in this method into setupClass method instead of setUp?

2017-11-03 11:11 UTC, ihtram commented
@ziafazal  i have added setUpClass() 
please review again

2017-11-03 11:51 UTC, ziafazal approved these changes
👍

2017-11-03 12:02 UTC, merged